const userConstants = {
  USER_UPDATE: 'USER_DETAILS_UPDATE',
  REQUEST: 'USER_REQUEST',
  REQUEST_FAILURE: 'USERS_REQUEST_FAILURE',
  CLEAR_ERRORS: 'CLEAR_USER_NOTIFICATION'
}

export default userConstants
